/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "android:332.300.002 ios:332170717.6329.0"
#endif /* AVUTIL_FFVERSION_H */
