platform :ios, '8.0'
install! 'cocoapods', :integrate_targets => true

target 'MultiCodecDemo' do
  pod 'SVProgressHUD'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = "NO"
    end
  end
end
