//
//  ffmpegframework.h
//  ffmpegframework
//
//  Created by IT on 2017/12/7.
//  Copyright © 2017年 IT. All rights reserved.
//

#import <UIKit/UIKit.h>
#import "libavcodec/avcodec.h"
#import "libavdevice/avdevice.h"
#import "libavfilter/avfilter.h"
#import "libavformat/avformat.h"
#import "libavresample/avresample.h"
#import "libavutil/avutil.h"
#import "libpostproc/postprocess.h"
#import "libswresample/swresample.h"
#import "libswscale/swscale.h"
#import "libx264/x264.h"
#import "libavformat/avformat.h"
#import "libavfilter/avfilter.h"
#import "libavdevice/avdevice.h"
#import "libavresample/avresample.h"
#import "libswscale/swscale.h"
#import "libswresample/swresample.h"
#import "libpostproc/postprocess.h"
#import "libavutil/avassert.h"
#import "libavutil/avstring.h"
#import "libavutil/bprint.h"
#import "libavutil/display.h"
#import "libavutil/mathematics.h"
#import "libavutil/imgutils.h"
#import "libavutil/libm.h"
#import "libavutil/parseutils.h"
#import "libavutil/pixdesc.h"
#import "libavutil/eval.h"
#import "libavutil/dict.h"
#import "libavutil/opt.h"
#import "libavutil/cpu.h"
#import "libavutil/ffversion.h"
#import "libavutil/version.h"
#import "libavcodec/avcodec.h"
#import "libavfilter/avfilter.h"
#import "libavformat/avformat.h"
#import "libswscale/swscale.h"
#import "libavformat/avformat.h"
#import "libavformat/avformat.h"
#import "libavdevice/avdevice.h"
#import "libswresample/swresample.h"
#import "libavutil/opt.h"
#import "libavutil/channel_layout.h"
#import "libavutil/parseutils.h"
#import "libavutil/samplefmt.h"
#import "libavutil/fifo.h"
#import "libavutil/hwcontext.h"
#import "libavutil/internal.h"
#import "libavutil/intreadwrite.h"
#import "libavutil/dict.h"
#import "libavutil/display.h"
#import "libavutil/mathematics.h"
#import "libavutil/pixdesc.h"
#import "libavutil/avstring.h"
#import "libavutil/libm.h"
#import "libavutil/imgutils.h"
#import "libavutil/timestamp.h"
#import "libavutil/bprint.h"
#import "libavutil/time.h"
#import "libavutil/threadmessage.h"
#import "libavcodec/mathops.h"
#import "libavformat/os_support.h"
#import "libavfilter/avfilter.h"
#import "libavfilter/buffersrc.h"
#import "libavfilter/buffersink.h"
#import "libavformat/avformat.h"
#import "libavformat/avio.h"
#import "libavcodec/avcodec.h"
#import "libavfilter/avfilter.h"
#import "libavutil/avutil.h"
#import "libavutil/dict.h"
#import "libavutil/eval.h"
#import "libavutil/fifo.h"
#import "libavutil/pixfmt.h"
#import "libavutil/rational.h"
#import "libavutil/threadmessage.h"
#import "libswresample/swresample.h"
#import "libavfilter/avfilter.h"
#import "libavfilter/buffersink.h"
#import "libavfilter/buffersrc.h"
#import "libavresample/avresample.h"
#import "libavutil/avassert.h"
#import "libavutil/avstring.h"
#import "libavutil/bprint.h"
#import "libavutil/channel_layout.h"
#import "libavutil/display.h"
#import "libavutil/opt.h"
#import "libavutil/pixdesc.h"
#import "libavutil/pixfmt.h"
#import "libavutil/imgutils.h"
#import "libavutil/samplefmt.h"
#import "libavformat/avformat.h"
#import "libavcodec/avcodec.h"
#import "libavfilter/avfilter.h"
#import "libavutil/avassert.h"
#import "libavutil/avstring.h"
#import "libavutil/avutil.h"
#import "libavutil/channel_layout.h"
#import "libavutil/intreadwrite.h"
#import "libavutil/fifo.h"
#import "libavutil/mathematics.h"
#import "libavutil/opt.h"
#import "libavutil/parseutils.h"
#import "libavutil/pixdesc.h"
#import "libavutil/pixfmt.h"
#import "libavformat/avformat.h"
#import "libavcodec/avcodec.h"
#import "libavutil/avassert.h"
#import "libavutil/avstring.h"
#import "libavutil/bprint.h"
#import "libavutil/display.h"
#import "libavutil/hash.h"
#import "libavutil/opt.h"
#import "libavutil/pixdesc.h"
#import "libavutil/spherical.h"
#import "libavutil/stereo3d.h"
#import "libavutil/dict.h"
#import "libavutil/intreadwrite.h"
#import "libavutil/libm.h"
#import "libavutil/parseutils.h"
#import "libavutil/timecode.h"
#import "libavutil/timestamp.h"
#import "libavdevice/avdevice.h"
#import "libswscale/swscale.h"
#import "libswresample/swresample.h"
#import "libpostproc/postprocess.h"
#import "libavutil/ffversion.h"
#import "libavutil/thread.h"

//! Project version number for ffmpegframework.
FOUNDATION_EXPORT double ffmpegframeworkVersionNumber;

//! Project version string for ffmpegframework.
FOUNDATION_EXPORT const unsigned char ffmpegframeworkVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <ffmpegframework/PublicHeader.h>


